services:
  # FastAPI Application
  api:
    build: .
    container_name: restaurant_pos_api
    restart: always
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: v11tech
      DB_PASSWORD: H91tB64qWe27
      DB_NAME: restaurant_pos
    ports:
      - "8003:8000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: bridge
