services:
  # FastAPI Application
  fastapi:
    build: .
    container_name: fastapi_app
    restart: unless-stopped
    network_mode: host
    environment:
      APP_ENV: development
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: restaurant_pos
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: supersecret
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
